language: java
os:
  - linux
jdk:
  - oraclejdk8

#matrix:
#  include:
#  - os: linux
#    jdk: oraclejdk8
#  - os: osx
#    osx_image: xcode8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "O0+XK4b7KaLr04YZNlhxch+HdFN4/sjQVDbk+IPxMO55GeJPmkHuTqUvUkmHZmpMzLW/ruqn7IWTM10Kna/Hf9V50yvzAOZyWmp0ih2PraMUDa97V/mXJeQQMXxrsnb89oOOrNDB15UjQA7dQbTVFZ1Dh8D7dyBo5OmPWyAiQZ/OEJsolZTFPiCbOTq920BfejMUzGAhtWXqgeHpBNGCvIho4a8cHIYOSI16OnFgi2TVJUN0JJaZIhjL8KaMCojchIDGc7u24MlD/2xwVbxsyqaLrDJ83WOBD4UW5SShhdb8/QVXB5fYwsIHLjSxGJMtjD5o1oGJrtZ4SsNd60pjtiDf7n2xFjYLezVdz1R+3HB4JshGuLLWw4aN8PqKBiqoolYKXXVejhy6jEL9D4tuynzygdYPB57RkXpKnEv1a7L2L18GSN2t0OEKrhU875sJtxQEcetHQwN5b9ObovBWlItnesxWRJEH5CoKgpZ1RkJsRn6dSUzCej+QC7oj9Mwv/TtBWv2c4ayV6ijsfGKYaNHqPRd4ZC93k8+7Pe06RfS9i0k/cXjRneiPn/fRbX0py/6QABdXmaQIBoCJWYsi6sUug/ynG+94D/UgsT/ncLgySYc+9xwfAiGg+Du9CRUOvLdSbZ6IdwatdjZytL8U4uKz5ga2ew79H0vvUD5tHMo="
   # The next declaration is the encrypted SONAR_TOKEN
   - secure: "qGawwy6qMugR0PJHbSQu+L5jEv7IsukJncvFevsC4SfvMdj0RNb/nj4NPZbtlxu3AJ3McxrAqEWWiekeXElVEBz4m9zm7NXuGQouV9ilHRRw8Y1BWSXlJVv5aIw55zCS1K40wjewSJmTw+qdmcocxVd99hA9kDMX0ZcBdT4T54F9ngqRJKyirtYWYv9RLQJvaKfOIX0vtzXRnqJateB4DSBF9SQGiEkF1megcsK829kAhrzuLKWamy5DfmxIRoTmBXCTxrL3T1yJWee6nf+dagtrCn3kqQQHtA0swRh9dUm/3lCMwDlXT+ewro79LgERXveVIVdMJtDRh8VsUvRMIJEBsXdQF6Yeahkoo/2pTgU5NJbo+BNQZ2mKb13987ChEQgIANOf15t4tE0IpLkUUqsdZPw3IwAnNybEmCazQWy4I422MO2zzxM5HqSCth2e6uc4KyDdsKWoowOxqVbvjPrxm1pX8RdBun7UyGSd9VF5PGh38i+TqsMo6GUEk5BcJeYiEhArnRN5Cqzyep2UHanIxPh1Y04yKQpC67+FMfRjhOeGkgn2h1V9PnCMjpxYzWeUFJyDABQebuwTBIX3CteivDzCos9R9VxG+kZQKfkgh+eiZtUjeKMjueLjbaO8ol9cyFNtB70YXVNYW66zQJFnPDqBqByNvd0EyF1+Amk="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "mkowalzik/spring-typescript-services"
      description: "Build submitted via Travis CI"
    notification_email: mathias.kowalzik@leandreck.org
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
  sonarcloud:
    organization: "leandreck-org" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
    branches:
      - master
      - development

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: qXSHcS4FY+mTuQGNoPwD0U5UIrnLRd+QJesPwpyIrmrtFbOk3BHDr2QqM3CECc69nG/EOtX5EgmC4ppgFQRAoy9uWFT8xk8ieaQI39ioGMQvMwyGDcblO0zrybxARCHyosMRup9D/ECOJIc3lnBMNlcnFLLnXsDjQA0u2aMVwKEZS9jTDKEEq99nCGBTJkpBxVNJS4BopJPQ92tawRHU4t4kJSd99u7GWvJlV/vu8rqYfF5hU1SHesYEC7ITe5e4Fo0g/yxWIbXhHIJzzbraDkq3BI+aHgGeDLM0Z9poeTg0jG8M6FLdLSG7AlwJOeTNX0T4qm7+Rmd74l73eLOp4M9ES5qedyw8hjfuTKjJGivhPFIkYxMaHkFr3I+ciMfUgfCy57ljzQ9gYHS8syL9jMIfCCQGxJdgyWLXsiXRQkqwBw2zgLr1YoHAU7bhgyIvN1FKj5i7HEOS+vmnkDEfM6DBTaoVsJC6vT9OJbbiLWaxvXlB+jUa2IRhsSKVkfIWxLCQmGhMF+1yu9K5bLo1ugnCg1c9IqN+GxWuNCZ+98lyGpFy14Upr+i1RyD36BUVnsQpB9oegTQuxxDIcjAqGkBJw9OX/rQn48AV2UtpSJM1BucRM8//x2CkQr9brPWGjN8hBcJpm/FxPoTWGuZakY9Nlt5ZdkdKAz/IqAlqOWY=
